### ISSUE TITLE
Unable to add maxLength to HashTagEditableText

### ISSUE THREAD

**Issue by nivla360** [santa112358/hashtagable#12]
I really need this please..

**Comment by santa112358** [comment]
@nivla360 
Now I noticed that the issue was about maxLength.  This is challenging because HashtagEditableText extends EditableText, which doesn't have the parameter like maxLength, but I will do my best to solve this problem. I will try to solve the problems with this package on next holidays. Thank you for the request.

**Comment by santa112358** [comment]
@nivla360 
Updated the version to 1.0.0 and solved this issue.
Thank you for the request.
