### ISSUE TITLE
Not support Arabic language 

### ISSUE THREAD

**Issue by hatemragab** [santa112358/hashtagable#24]
Not support Arabic language please support Arabic language which is rtl language thanks

**Comment by PattaraponLertratananont** [comment]
Thai language not support same

**Comment by santa112358** [comment]
@hatemragab @PattaraponLertratananont 

Thank you for the requests. I will try to update the package to support Arabic and Thai, but it might take a little while because I've never touched both of the languages. 

This is the regular expression code which picks up the hashtag text properly in Japanese, English and Spanish.
https://github.com/santa112358/hashtagable/blob/master/lib/decorator.dart#L23-L26
If you have any idea about the regular expression in your own language, let me know how to fix that.

**Comment by santa112358** [comment]
@hatemragab @PattaraponLertratananont 
I updated the version to 1.0.1 which supports Arabic and Thai, but it may have some problems, so please reopen this issue or create new one if you find problems. Now I close this issue. Thank you.
