### ISSUE TITLE
HashTagText not showing other characters 

### ISSUE THREAD

**Issue by NaMeTaKeN33** [santa112358/hashtagable#28]
v. 1.0.1

Adding special characters (!?. etc) should not break the hashtag, however it is currently removing the characters from display.

For example. The text "#hello!" shows up as "**_#hello_**" where it should show up as "**_#hello_**!" with the exclamation mark using the basicStyle option.

**Comment by santa112358** [comment]
@NaMeTaKeN33 
Thank you for creating issue.
Since the [decoration rule](https://pub.dev/packages/hashtagable#tips) is following that of Twitter, it doesn't decorate exclamation and question mark as hashtag. 

I suggest you to customize the code [here](https://github.com/santa112358/hashtagable/blob/master/lib/decorator/hashtag_regular_expression.dart#L1), in your project.
 
Currently it is `const _Symbols = '·・ー_';`, but you can enable it to decorate exclamation and question mark by changing the value into `const _Symbols = '·・ー_!?';`

**Comment by NaMeTaKeN33** [comment]
I think you're mis-understanding. It's not that the "!" is not decorated. It's that it gets completely deleted/removed. However when re-loading my emulator to take screen-shots of the issue, it appears that it's now working correctly.

Going to close this issue as an emulator issue and not a bug.
